from operator import ne
from pyfiveoneone.client import Client
from pyfiveoneone.autogenerated.stops import Stops
from pathlib import Path
import json
import pandas as pd


def add_one(number):
    return number + 1


client = Client()

stop = Stops.REDWOOD_CITY_CALTRAIN_STATION_NORTHBOUND.value

next_stops = client.scheduled_departures_at_stop("CT", stop.stop_id)
with open("next_stops.json", "w") as f:
    json.dump(next_stops, f, indent=4)


# stop_times_df = pd.read_csv(
#     Path(__file__).parent
#     / "autogenerated"
#     / "inputs"
#     / "GTFSTransitData_CT"
#     / "stop_times.txt"
# )
# print(
#     stop_times_df[
#         (stop_times_df["stop_id"] == stop.stop_id) & (stop_times_df["trip_id"] == 401)
#     ]
# )

# resp = client.real_time_stop_monitoring("CT", stopcode=stop.stop_code)

# with open("real_time_stop_monitoring.json", "w") as f:
#     json.dump(resp, f, indent=4)

# resp = client.get_operators()
# with open("gtfs_operators.json", "w") as f:
#     json.dump(resp, f, indent=4)

# resp = client.gfts_rt_trip_updates("CT")
# with open("resp.json", "w") as f:
#     json.dump(resp, f, indent=4)
