from pyfiveoneone.client import Client
import json
from pathlib import Path

out_dir = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "pyfiveoneone"
    / "autogenerated"
    / "inputs"
)
out_dir.mkdir(exist_ok=True)

client = Client()

gtfs_operators = client.gtfs_operators()
with open(out_dir / "gtfs_operators.json", "w", encoding="utf-8") as f:
    json.dump(gtfs_operators, f, indent=4)

# client.gtfs_feed_download("CT", str(out_dir / "ct_gtfs.zip"))
# gtfs_feed_list = client.gtfs_feed_list("CT")
# with open(out_dir / "gtfs_feed_list.json", "w", encoding="utf-8") as f:
#     json.dump(gtfs_feed_list, f, indent=4)
