# Auto-generated by scripts/autogen_models.py
# Do not edit by hand
# Version: 4
# Generated: 2025-09-08T06:13:56Z
from enum import Enum
from ..models import CalendarAttribute

# === BEGIN ENUM BODY ===
class CalendarAttributes(Enum):
	"""Autocomplete-friendly enumeration of CalendarAttribute rows.

	Access dataclass instances via: CalendarAttributes.FOO.value
	"""
	WEEKDAY = CalendarAttribute(service_id=72981, service_description='Weekday')
	WEEKEND = CalendarAttribute(service_id=72982, service_description='Weekend')
# === END ENUM BODY ===
