# Auto-generated by scripts/autogen_models.py
# Do not edit by hand
# Version: 3
# Generated: 2025-09-08T06:13:56Z
from enum import Enum
from ..models import Direction

# === BEGIN ENUM BODY ===
class Directions(Enum):
	"""Autocomplete-friendly enumeration of Direction rows.

	Access dataclass instances via: Directions.FOO.value
	"""
	NORTH = Direction(route_id='Express', direction_id=0, direction_name='North')
	NORTH_LIMITED = Direction(route_id='Limited', direction_id=0, direction_name='North')
	NORTH_LOCAL WEEKDAY = Direction(route_id='Local Weekday', direction_id=0, direction_name='North')
	NORTH_LOCAL WEEKEND = Direction(route_id='Local Weekend', direction_id=0, direction_name='North')
	NORTH_SOUTH COUNTY = Direction(route_id='South County', direction_id=0, direction_name='North')
	SOUTH = Direction(route_id='Express', direction_id=1, direction_name='South')
	SOUTH_LIMITED = Direction(route_id='Limited', direction_id=1, direction_name='South')
	SOUTH_LOCAL WEEKDAY = Direction(route_id='Local Weekday', direction_id=1, direction_name='South')
	SOUTH_LOCAL WEEKEND = Direction(route_id='Local Weekend', direction_id=1, direction_name='South')
	SOUTH_SOUTH COUNTY = Direction(route_id='South County', direction_id=1, direction_name='South')
# === END ENUM BODY ===
