# Auto-generated by scripts/autogen_models.py
# Do not edit by hand
# Version: 4
# Generated: 2025-09-08T06:13:56Z
from enum import Enum
from ..models import Route

# === BEGIN ENUM BODY ===
class Routes(Enum):
	"""Autocomplete-friendly enumeration of Route rows.

	Access dataclass instances via: Routes.FOO.value
	"""
	EXPRESS = Route(route_id='Express', agency_id='CT', route_short_name='Express', route_long_name='', route_desc='', route_type='2', route_url='', route_color='ce202f', route_text_color='ffffff')
	LIMITED = Route(route_id='Limited', agency_id='CT', route_short_name='Limited', route_long_name='', route_desc='', route_type='2', route_url='', route_color='99d7dc', route_text_color='000000')
	LOCAL_WEEKDAY = Route(route_id='Local Weekday', agency_id='CT', route_short_name='Local Weekday', route_long_name='', route_desc='', route_type='2', route_url='', route_color='dcddde', route_text_color='000000')
	LOCAL_WEEKEND = Route(route_id='Local Weekend', agency_id='CT', route_short_name='Local Weekend', route_long_name='', route_desc='', route_type='2', route_url='', route_color='dcddde', route_text_color='000000')
	SOUTH_SANTA_CLARA_COUNTY_CONNECTOR = Route(route_id='South County', agency_id='CT', route_short_name='South County', route_long_name='South Santa Clara County Connector', route_desc='', route_type='2', route_url='', route_color='fae4a7', route_text_color='000000')
# === END ENUM BODY ===
